---
ID: "05289b4a-1026-470d-a8ee-d65a6d69e0b3"
Parent: "23671be4-84cf-4d31-b430-88f3c42cec1c"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: "/sitecore/templates/Sitecore Cognitive Services - Ole Chat/Ole Chat Settings/Ole Chat/Application Id"
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: "Single-Line Text"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180210T194306Z
