---
ID: "404d62d3-378d-4076-9d41-058960dd1548"
Parent: "715d655a-5f9d-41ad-b4d0-6b1a79a51eb9"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Sitecore Cognitive Services/Image Search/Image Search Settings/Image Search Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180127T055258Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
