using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Microsoft.SharedSource.CognitiveServices.Enums;
using Microsoft.SharedSource.CognitiveServices.Models.Vision.ContentModerator;

namespace Microsoft.SharedSource.CognitiveServices.Repositories.Vision {
    public interface IContentModeratorRepository
    {
        EvaluateResponse Evaluate(string imageUrl);
        Task<EvaluateResponse> EvaluateAsync(string imageUrl);
        EvaluateResponse Evaluate(Stream stream);
        Task<EvaluateResponse> EvaluateAsync(Stream stream);
        FindFacesResponse FindFaces(string imageUrl);
        Task<FindFacesResponse> FindFacesAsync(string imageUrl);
        FindFacesResponse FindFaces(Stream stream);
        Task<FindFacesResponse> FindFacesAsync(Stream stream);
        MatchResponse Match(string imageUrl, string listId = "");
        Task<MatchResponse> MatchAsync(string imageUrl, string listId = "");
        MatchResponse Match(Stream stream, string listId = "");
        Task<MatchResponse> MatchAsync(Stream stream, string listId = "");
        OCRResult OCR(string imageUrl, string language = "", bool enhanced = false);
        Task<OCRResult> OCRAsync(string imageUrl, string language = "", bool enhanced = false);
        OCRResult OCR(Stream stream, string language = "", bool enhanced = false);
        Task<OCRResult> OCRAsync(Stream stream, string language = "", bool enhanced = false);
        DetectLanguageResponse DetectLanguage(string text);
        Task<DetectLanguageResponse> DetectLanguageAsync(string text);
        ScreenResponse Screen(string text, string language = "eng", bool autocorrect = false, bool urls = false, bool PII = false, string listId = "");
        Task<ScreenResponse> ScreenAsync(string text, string language = "eng", bool autocorrect = false, bool urls = false, bool PII = false, string listId = "");
        CreateJobResponse CreateImageJob(string imageUrl, string teamName, string contentId, string workflowName, string callbackEndpoint = "");
        Task<CreateJobResponse> CreateImageJobAsync(string imageUrl, string teamName, string contentId, string workflowName, string callbackEndpoint = "");
        CreateJobResponse CreateImageJob(Stream stream, string teamName, string contentId, string workflowName, string callbackEndpoint = "");
        Task<CreateJobResponse> CreateImageJobAsync(Stream stream, string teamName, string contentId, string workflowName, string callbackEndpoint = "");
        CreateJobResponse CreateTextJob(string text, string teamName, string contentId, string workflowName, string callbackEndpoint = "");
        Task<CreateJobResponse> CreateTextJobAsync(string text, string teamName, string contentId, string workflowName, string callbackEndpoint = "");
        GetJobResponse GetJob(string teamName, string jobId);
        Task<GetJobResponse> GetJobAsync(string teamName, string jobId);
        List<string> CreateReview(string teamName, List<ReviewRequest> requests, string subTeam = "");
        Task<List<string>> CreateReviewAsync(string teamName, List<ReviewRequest> requests, string subTeam = "");
        GetReviewResponse GetReview(string teamName, string reviewId);
        Task<GetReviewResponse> GetReviewAsync(string teamName, string reviewId);
        bool CreateOrUpdateWorkflow(string teamName, string workflowName, WorkflowExpression expression);
        Task<bool> CreateOrUpdateWorkflowAsync(string teamName, string workflowName, WorkflowExpression expression);
        WorkflowExpressionResponse GetWorkflow(string teamName, string workflowName);
        Task<WorkflowExpressionResponse> GetWorkflowAsync(string teamName, string workflowName);
        List<WorkflowExpressionResponse> GetAllWorkflows(string teamName);
        Task<List<WorkflowExpressionResponse>> GetAllWorkflowsAsync(string teamName);
        AddImageResponse AddImage(string imageUrl, string listId, ContentModeratorTag tag = ContentModeratorTag.None, string label = "");
        Task<AddImageResponse> AddImageAsync(string imageUrl, string listId, ContentModeratorTag tag = ContentModeratorTag.None, string label = "");
        AddImageResponse AddImage(Stream stream, string listId, ContentModeratorTag tag = ContentModeratorTag.None, string label = "");
        Task<AddImageResponse> AddImageAsync(Stream stream, string listId, ContentModeratorTag tag = ContentModeratorTag.None, string label = "");
        void DeleteImage(string listId, string imageId);
        Task DeleteImageAsync(string listId, string imageId);
        void DeleteAllImage(string listId);
        Task DeleteAllImageAsync(string listId);
        GetImagesResponse GetAllImageIds(string listId);
        Task<GetImagesResponse> GetAllImageIdsAsync(string listId);
        ListDetails GetImageListDetails(string listId);
        Task<ListDetails> GetImageListDetailsAsync(string listId);
        ListDetails CreateList(ListDetails details);
        Task<ListDetails> CreateListAsync(ListDetails details);
        void DeleteImageList(string listId);
        Task DeleteImageListAsync(string listId);
        List<ListDetails> GetAllImageLists();
        Task<List<ListDetails>> GetAllImageListsAsync();
        RefreshSearchResponse RefreshImageSearchIndex(string listId);
        Task<RefreshSearchResponse> RefreshImageSearchIndexAsync(string listId);
        ListDetails UpdateImageListDetails(string listId, ListDetails details);
        Task<ListDetails> UpdateImageListDetailsAsync(string listId, ListDetails details);
        void AddTerm(string listId, string term, string language);
        Task AddTermAsync(string listId, string term, string language);
        void DeleteTerm(string listId, string term, string language);
        Task DeleteTermAsync(string listId, string term, string language);
        void DeleteAllTerms(string listId, string language);
        Task DeleteAllTermsAsync(string listId, string language);
        GetTermsResponse GetAllTerms(string listId, string language);
        Task<GetTermsResponse> GetAllTermsAsync(string listId, string language);
        ListDetails CreateTermList(ListDetails details);
        Task<ListDetails> CreateTermListAsync(ListDetails details);
        void DeleteTermList(string listId);
        Task DeleteTermListAsync(string listId);
        List<ListDetails> GetAllTermLists();
        Task<List<ListDetails>> GetAllTermListsAsync();
        ListDetails GetTermListDetails(string listId);
        Task<ListDetails> GetTermListDetailsAsync(string listId);
        RefreshSearchResponse RefreshTermSearchIndex(string listId, string language);
        Task<RefreshSearchResponse> RefreshTermSearchIndexAsync(string listId, string language);
        ListDetails UpdateTermListDetails(string listId, ListDetails details);
        Task<ListDetails> UpdateTermListDetailsAsync(string listId, ListDetails details);
    }
}